all:
	gcc array.c -o array.out
	cat array.c | ./array.out
	gcc word_lengths_histogram.c -o word_lengths_histogram.out
	cat word_lengths_histogram.c | ./word_lengths_histogram.out
	gcc character_counts.c -o character_counts.out
	cat character_counts.c | ./character_counts.out
